export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  STAFF: 'STAFF',
  CUSTOMER: 'CUSTOMER'
};

export const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF];

export const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: 5,
  [ROLES.ADMIN]: 4,
  [ROLES.MANAGER]: 3,
  [ROLES.STAFF]: 2,
  [ROLES.CUSTOMER]: 1
};

export const PERMISSIONS = {
  MANAGE_USERS: [ROLES.SUPER_ADMIN],
  MANAGE_PRODUCTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  MANAGE_INVENTORY: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  MANAGE_ORDERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
  VIEW_ANALYTICS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  MANAGE_CMS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  RESET_CMS: [ROLES.SUPER_ADMIN]
};
